//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class active_ingredient_pula
    {
        public int pula_id { get; set; }
        public int pula_shape_id { get; set; }
        public string other_justification { get; set; }
        public string base_data { get; set; }
        public string base_data_modifiers { get; set; }
        public string interim_proposed_decision { get; set; }
        public string focus_meeting { get; set; }
        public string biological_opinion_regreview { get; set; }
        public string biological_opinion_lit { get; set; }
        public string proposed_decision { get; set; }
        public int version_id { get; set; }
        public int id { get; set; }
        public int is_published { get; set; }
        public Nullable<System.DateTime> effective_date { get; set; }
        public Nullable<int> event_id { get; set; }
        public string comments { get; set; }
        public string sec3_newchem { get; set; }
        public string sec3_newuse { get; set; }
        public string sec24 { get; set; }
        public string final_decision { get; set; }
        public string sec18 { get; set; }
        public string interim_decision { get; set; }
        public string additional_information { get; set; }
    
        public virtual version version { get; set; }
        public virtual @event @event { get; set; }
    }
}
