//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLTDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bltEntities : DbContext
    {
        public bltEntities()
            : base("name=bltEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<active_ingredient> active_ingredient { get; set; }
        public DbSet<active_ingredient_ai_class> active_ingredient_ai_class { get; set; }
        public DbSet<active_ingredient_pula> active_ingredient_pula { get; set; }
        public DbSet<ai_class> ai_class { get; set; }
        public DbSet<application_method> application_method { get; set; }
        public DbSet<crop_use> crop_use { get; set; }
        public DbSet<division> divisions { get; set; }
        public DbSet<@event> events { get; set; }
        public DbSet<formulation> formulations { get; set; }
        public DbSet<limitation> limitations { get; set; }
        public DbSet<organization> organizations { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<product_active_ingredient> product_active_ingredient { get; set; }
        public DbSet<pula_limitations> pula_limitations { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<species_active_ingredient_pula> species_active_ingredient_pula { get; set; }
        public DbSet<user_> user_ { get; set; }
        public DbSet<version> versions { get; set; }
    }
}
