//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class division
    {
        public division()
        {
            this.user_ = new HashSet<user_>();
        }
    
        public int division_id { get; set; }
        public string division_name { get; set; }
    
        public virtual ICollection<user_> user_ { get; set; }
    }
}
