//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class @event
    {
        public @event()
        {
            this.active_ingredient_pula = new HashSet<active_ingredient_pula>();
        }
    
        public int event_id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<active_ingredient_pula> active_ingredient_pula { get; set; }
    }
}
