//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int product_id { get; set; }
        public string product_registration_number { get; set; }
        public string product_name { get; set; }
        public int version_id { get; set; }
        public int id { get; set; }
        public string product_name_status { get; set; }
    
        public virtual version versions { get; set; }
    }
}
