//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class pula_limitations
    {
        public int pula_limitation_id { get; set; }
        public Nullable<int> active_ingredient_id { get; set; }
        public Nullable<int> limitation_id { get; set; }
        public Nullable<int> crop_use_id { get; set; }
        public Nullable<int> application_method_id { get; set; }
        public int version_id { get; set; }
        public int pula_id { get; set; }
        public Nullable<int> formulation_id { get; set; }
        public Nullable<int> product_id { get; set; }
    
        public virtual version version { get; set; }
    }
}
