//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_
    {
        public user_()
        {
            this.versions = new HashSet<version>();
            this.versions1 = new HashSet<version>();
            this.versions2 = new HashSet<version>();
        }
    
        public int user_id { get; set; }
        public string username { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> division_id { get; set; }
        public int role_id { get; set; }
        public string fname { get; set; }
        public string lname { get; set; }
        public string password { get; set; }
        public string salt { get; set; }
        public Nullable<int> resetFlag { get; set; }
    
        public virtual ICollection<version> versions { get; set; }
        public virtual ICollection<version> versions1 { get; set; }
        public virtual ICollection<version> versions2 { get; set; }
        public virtual organization organization { get; set; }
        public virtual division division { get; set; }
        public virtual role role { get; set; }
    }
}
