//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLTDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class version
    {
        public version()
        {
            this.active_ingredient_pula = new HashSet<active_ingredient_pula>();
            this.pula_limitations = new HashSet<pula_limitations>();
            this.formulations = new HashSet<formulation>();
            this.application_method = new HashSet<application_method>();
            this.crop_use = new HashSet<crop_use>();
            this.limitations = new HashSet<limitation>();
            this.species_active_ingredient_pula = new HashSet<species_active_ingredient_pula>();
            this.ai_class = new HashSet<ai_class>();
            this.active_ingredient_ai_class = new HashSet<active_ingredient_ai_class>();
            this.product_active_ingredient = new HashSet<product_active_ingredient>();
            this.product = new HashSet<product>();
            this.active_ingredient = new HashSet<active_ingredient>();
        }
    
        public int version_id { get; set; }
        public Nullable<int> creator_id { get; set; }
        public Nullable<System.DateTime> created_time_stamp { get; set; }
        public Nullable<int> publisher_id { get; set; }
        public Nullable<System.DateTime> published_time_stamp { get; set; }
        public Nullable<int> expirer_id { get; set; }
        public Nullable<System.DateTime> expired_time_stamp { get; set; }
        public Nullable<int> reviewer_id { get; set; }
        public Nullable<System.DateTime> reviewed_time_stamp { get; set; }
    
        public virtual ICollection<active_ingredient_pula> active_ingredient_pula { get; set; }
        public virtual ICollection<pula_limitations> pula_limitations { get; set; }
        public virtual ICollection<formulation> formulations { get; set; }
        public virtual ICollection<application_method> application_method { get; set; }
        public virtual ICollection<crop_use> crop_use { get; set; }
        public virtual ICollection<limitation> limitations { get; set; }
        public virtual ICollection<species_active_ingredient_pula> species_active_ingredient_pula { get; set; }
        public virtual user_ Publisher { get; set; }
        public virtual user_ Creator { get; set; }
        public virtual user_ Expirer { get; set; }
        public virtual ICollection<ai_class> ai_class { get; set; }
        public virtual ICollection<active_ingredient_ai_class> active_ingredient_ai_class { get; set; }
        public virtual ICollection<product_active_ingredient> product_active_ingredient { get; set; }
        public virtual ICollection<product> product { get; set; }
        public virtual ICollection<active_ingredient> active_ingredient { get; set; }
    }
}
